### ISSUE TITLE
Launch checklist for doc pages

### ISSUE THREAD

**Issue by rmglennon** [mapzen/documentation#24]
- [x] Title text is present
- [x] Title text is consistent with product names (for example, Mapzen Turn-by-Turn, rather than Valhalla)
- [x] Page has links to the related project or data page
- [x] Page content and formatting is relatively consistent across products (for example, some have bullet lists, others are paragraphs, or have only a title)
- [x] Title banner across the top is present and consistent (for example, some have wide images, some have gray bar, some have subheadings underneath)
- [x] Search box is present and working
- [x] Breadcrumbs are present and working
